[package]
name = "ttdash"
version = "0.1.0"
authors = ["Matt Jones <jonesmr@gmail.com>"]

[dependencies]
chrono = "*"
chrono-tz = "*"
getopts = "*"
image = "*"
imageproc = "*"
protobuf = "*"
reqwest = "*"
rppal = "*"
rusttype = "^0.5"
serde = "*"
serde_derive = "*"
serde_json = "*"
